### PR TITLE
Debug clang-19 failure

### PR DESCRIPTION
**Pull request by steve-downey**

### CODE REVIEW

**Comment by JeffGarland** [comment]
Seems like clang 17 isn't quite up to the task, do we really care? Seems likely that the ongoing 'what compilers' to support discussion will continue to heat up as we do real work.

**Comment by steve-downey** [comment]
It is bothering me because it appears to work on my machine. But I think
that is because I happen to have the libc++ from 19 installed, and that
avoids the particular error.
Libc++ from 17 did not have join, so sone tests fail.
It may not be worth going back to clang-17, though, I agree.

**Comment by neatudarius** [comment]
@steve-downey , I merged #9 . You can update your branch to see why the clang-19 job failed on that particular job/code.

**Comment by steve-downey** [comment]
I'll put up a cleaner PR now that this is working.

**Pull request closed without merging**
